// GENERATED BY make_perl_groups.pl; DO NOT EDIT.
// make_perl_groups.pl >perl_groups.cc

#include "re2/unicode_groups.h"

namespace re2 {

static URange32 code1[] = {  /* \d */
	{ 0x30, 0x39 },
};
static URange32 code2[] = {  /* \D */
	{ 0x0, 0x2f },
	{ 0x3a, 0x10ffff },
};
static URange32 code3[] = {  /* \s */
	{ 0x9, 0xa },
	{ 0xc, 0xd },
	{ 0x20, 0x20 },
};
static URange32 code4[] = {  /* \S */
	{ 0x0, 0x8 },
	{ 0xb, 0xb },
	{ 0xe, 0x1f },
	{ 0x21, 0x10ffff },
};
static URange32 code5[] = {  /* \w */
	{ 0x30, 0x39 },
	{ 0x41, 0x5a },
	{ 0x5f, 0x5f },
	{ 0x61, 0x7a },
};
static URange32 code6[] = {  /* \W */
	{ 0x0, 0x2f },
	{ 0x3a, 0x40 },
	{ 0x5b, 0x5e },
	{ 0x60, 0x60 },
	{ 0x7b, 0x10ffff },
};
static URange32 code7[] = {  /* \D */
	{ 0x0, 0x2f },
	{ 0x3a, 0x10ffff },
};
UGroup perl_groups[] = {
	{ "\\d", 0, 0, code1, 1 },
	{ "\\D", 0, 0, code2, 2 },
	{ "\\s", 0, 0, code3, 3 },
	{ "\\S", 0, 0, code4, 4 },
	{ "\\w", 0, 0, code5, 4 },
	{ "\\W", 0, 0, code6, 5 },
	{ "\\D", 0, 0, code7, 2 },
};
int num_perl_groups = 7;
static URange32 code8[] = {  /* [:alnum:] */
	{ 0x30, 0x39 },
	{ 0x41, 0x5a },
	{ 0x61, 0x7a },
};
static URange32 code9[] = {  /* [:^alnum:] */
	{ 0x0, 0x2f },
	{ 0x3a, 0x40 },
	{ 0x5b, 0x60 },
	{ 0x7b, 0x10ffff },
};
static URange32 code10[] = {  /* [:alpha:] */
	{ 0x41, 0x5a },
	{ 0x61, 0x7a },
};
static URange32 code11[] = {  /* [:^alpha:] */
	{ 0x0, 0x40 },
	{ 0x5b, 0x60 },
	{ 0x7b, 0x10ffff },
};
static URange32 code12[] = {  /* [:ascii:] */
	{ 0x0, 0x7f },
};
static URange32 code13[] = {  /* [:^ascii:] */
	{ 0x80, 0x10ffff },
};
static URange32 code14[] = {  /* [:blank:] */
	{ 0x9, 0x9 },
	{ 0x20, 0x20 },
};
static URange32 code15[] = {  /* [:^blank:] */
	{ 0x0, 0x8 },
	{ 0xa, 0x1f },
	{ 0x21, 0x10ffff },
};
static URange32 code16[] = {  /* [:cntrl:] */
	{ 0x0, 0x1f },
	{ 0x7f, 0x7f },
};
static URange32 code17[] = {  /* [:^cntrl:] */
	{ 0x20, 0x7e },
	{ 0x80, 0x10ffff },
};
static URange32 code18[] = {  /* [:digit:] */
	{ 0x30, 0x39 },
};
static URange32 code19[] = {  /* [:^digit:] */
	{ 0x0, 0x2f },
	{ 0x3a, 0x10ffff },
};
static URange32 code20[] = {  /* [:graph:] */
	{ 0x21, 0x7e },
};
static URange32 code21[] = {  /* [:^graph:] */
	{ 0x0, 0x20 },
	{ 0x7f, 0x10ffff },
};
static URange32 code22[] = {  /* [:lower:] */
	{ 0x61, 0x7a },
};
static URange32 code23[] = {  /* [:^lower:] */
	{ 0x0, 0x60 },
	{ 0x7b, 0x10ffff },
};
static URange32 code24[] = {  /* [:print:] */
	{ 0x20, 0x7e },
};
static URange32 code25[] = {  /* [:^print:] */
	{ 0x0, 0x1f },
	{ 0x7f, 0x10ffff },
};
static URange32 code26[] = {  /* [:punct:] */
	{ 0x21, 0x2f },
	{ 0x3a, 0x40 },
	{ 0x5b, 0x60 },
	{ 0x7b, 0x7e },
};
static URange32 code27[] = {  /* [:^punct:] */
	{ 0x0, 0x20 },
	{ 0x30, 0x39 },
	{ 0x41, 0x5a },
	{ 0x61, 0x7a },
	{ 0x7f, 0x10ffff },
};
static URange32 code28[] = {  /* [:space:] */
	{ 0x9, 0xd },
	{ 0x20, 0x20 },
};
static URange32 code29[] = {  /* [:^space:] */
	{ 0x0, 0x8 },
	{ 0xe, 0x1f },
	{ 0x21, 0x10ffff },
};
static URange32 code30[] = {  /* [:upper:] */
	{ 0x41, 0x5a },
};
static URange32 code31[] = {  /* [:^upper:] */
	{ 0x0, 0x40 },
	{ 0x5b, 0x10ffff },
};
static URange32 code32[] = {  /* [:word:] */
	{ 0x30, 0x39 },
	{ 0x41, 0x5a },
	{ 0x5f, 0x5f },
	{ 0x61, 0x7a },
};
static URange32 code33[] = {  /* [:^word:] */
	{ 0x0, 0x2f },
	{ 0x3a, 0x40 },
	{ 0x5b, 0x5e },
	{ 0x60, 0x60 },
	{ 0x7b, 0x10ffff },
};
static URange32 code34[] = {  /* [:xdigit:] */
	{ 0x30, 0x39 },
	{ 0x41, 0x46 },
	{ 0x61, 0x66 },
};
static URange32 code35[] = {  /* [:^xdigit:] */
	{ 0x0, 0x2f },
	{ 0x3a, 0x40 },
	{ 0x47, 0x60 },
	{ 0x67, 0x10ffff },
};
UGroup posix_groups[] = {
	{ "[:alnum:]", 0, 0, code8, 3 },
	{ "[:^alnum:]", 0, 0, code9, 4 },
	{ "[:alpha:]", 0, 0, code10, 2 },
	{ "[:^alpha:]", 0, 0, code11, 3 },
	{ "[:ascii:]", 0, 0, code12, 1 },
	{ "[:^ascii:]", 0, 0, code13, 1 },
	{ "[:blank:]", 0, 0, code14, 2 },
	{ "[:^blank:]", 0, 0, code15, 3 },
	{ "[:cntrl:]", 0, 0, code16, 2 },
	{ "[:^cntrl:]", 0, 0, code17, 2 },
	{ "[:digit:]", 0, 0, code18, 1 },
	{ "[:^digit:]", 0, 0, code19, 2 },
	{ "[:graph:]", 0, 0, code20, 1 },
	{ "[:^graph:]", 0, 0, code21, 2 },
	{ "[:lower:]", 0, 0, code22, 1 },
	{ "[:^lower:]", 0, 0, code23, 2 },
	{ "[:print:]", 0, 0, code24, 1 },
	{ "[:^print:]", 0, 0, code25, 2 },
	{ "[:punct:]", 0, 0, code26, 4 },
	{ "[:^punct:]", 0, 0, code27, 5 },
	{ "[:space:]", 0, 0, code28, 2 },
	{ "[:^space:]", 0, 0, code29, 3 },
	{ "[:upper:]", 0, 0, code30, 1 },
	{ "[:^upper:]", 0, 0, code31, 2 },
	{ "[:word:]", 0, 0, code32, 4 },
	{ "[:^word:]", 0, 0, code33, 5 },
	{ "[:xdigit:]", 0, 0, code34, 3 },
	{ "[:^xdigit:]", 0, 0, code35, 4 },
};
int num_posix_groups = 28;

}  // namespace re2
